### PR TITLE
[ratel] add nickname to terminal

### PR DESCRIPTION
**Pull request by GOODDAYDAY**
Hi All,
    It is a meaningless pr about adding the nickname to terminal.
    1. The format is `[{nickname}:ratel@{message}]`
    2. The init nickname is `player`
    3. When send the `CODE_CLIENT_NICKNAME_SET` event, client will save the nickname to User.INSTANCE

Regards,
Goody

P.S.: It is my first time to pr. If there are something uncomfortable, please feel free to connect me.

### CODE REVIEW

**Comment by ainilili** [comment]
Hi Goody! 

Thanks for your contributions, the changes looked too much repetitive logic.

I think you can overwrite method ``public static String write(String message)`` and to implement new terminal formated like ``[{nickname}@{message}]``.

Can you make a simple changes? I will merged to master after this!

**Comment by GOODDAYDAY** [comment]
Hi Nico!

Thanks for your reply!

I understand the format part.The `write()` part means a new `PrintUtils` in `Client` module? The `SimpleWriter` is in `Common` module and can not import the `User entity`.

Regards,
Goody

**Comment by GOODDAYDAY** [comment]
Hi Nico! 

Actually, I noticed that there is a issue about collecting the message to properties.The new Writer can handle the biz part.

Regards,
Goody

**Comment by ainilili** [comment]
Merged!

**Pull request merged**
